manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: andre-tm-hui
      url-base: https://github.com/andre-tm-hui
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.2
      import: app/west.yml
    - name: zmk-pmw3XXX-driver
      remote: andre-tm-hui
      revision: pmw3360
  self:
    path: config
